# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nick Nance
tagline:          Thoughts on CoSo Engineering
url:              http://nickcs.github.io/blog/
paginate:         1
baseurl:          /
author:
  name:           Nick Nance
  url:            https://github.com/nickcs
  email:          nick.nance@connectsolutions.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/nickcs/poole
